### ISSUE TITLE
Jupyterlab extentions

### ISSUE THREAD

**Issue by Casyfill** [mapbox/mapboxgl-jupyter#67]
Not exactly related to this project, but still - it would be awesome to have an alternative geojson extension (or alternative engine for the same extension), as current jupyterlab geojson viewer is very, very slow

https://github.com/jupyterlab/jupyter-renderers

**Comment by ryanbaumann** [comment]
Great idea @casyfill!  Since jupyterlab extensions are all written in JavaScript, it would be relatively straightforward to just replace the leaflet.js implementation of the geojson viewer with Mapbox GL JS.  This mapboxgl-jupyter Python library is a useful reference implementation, but I would recommend starting from the vanilla Mapbox GL JS library for this solution.  Happy to support you if you have any questions making a PR there.

**Comment by Juanlu001** [comment]
@ryanbaumann May I ask, in which pull request was this closed?

**Comment by ryanbaumann** [comment]
@Juanlu001I should have added a comment here, apologies.  I closed this issue  because it doesn't directly relate to the `mapboxgl-jupyter` library.  The idea here is to replace `leaflet.js` with `mapboxgl.js` in another Jupyter Lab extension, https://github.com/jupyterlab/jupyter-renderers.

I opened a ticket in https://github.com/jupyterlab/jupyter-renderers/issues/116 to track there.
