### ISSUE TITLE
Improve Legend Design

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapboxgl-jupyter#80]
The current default legend is very basic - we should improve the design with a bit of CSS magic.

![](https://cl.ly/040l2i2k2Q1V/download/Image%202018-03-25%20at%206.58.40%20PM.png)

**Comment by akacarlyann** [comment]
I think this could go well with generalizing the function for creating the legend, too!  Right now I have a hack in the __ChoroplethViz__ class that styles the legend symbols as rounded squares instead of circles.  Are you thinking of inline CSS with Jupyter or defining more style components in __viz.py__?  I'm happy to work on this a bit.

**Comment by ryanbaumann** [comment]
Yes, that would be excellent @akacarlyann.  There's lots of inspiration to take for great design - are you confident with design, or would you prefer to start with some suggested designs?

As far as how to compile the CSS - if we're going to make the stylesheet bigger, I recommend breaking it out into it's own `templates/style` directory, and loading the css files you need using Jinja templates.

**Comment by akacarlyann** [comment]
If you've got an idea in mind, I'm happy to take a look.  Otherwise my thought was to start with centering the legend title and possibly adding a color-background to the header.  Otherwise, feel free to point me in a different direction.
<img width="136" alt="screen shot 2018-03-28 at 9 53 29 pm" src="https://user-images.githubusercontent.com/13527707/38070775-7a962530-32d2-11e8-9d9f-169e505511aa.png"> 
<img width="140" alt="screen shot 2018-03-28 at 10 06 37 pm" src="https://user-images.githubusercontent.com/13527707/38071112-56fc3d24-32d4-11e8-9658-b32f3a254181.png">

**Comment by bchowTWC** [comment]
Apologies for hijacking, didn't want to create another issue on a related topic...

Background: one of my use cases involves dropping a polygon on the map from a single geojson feature and filling in the enclosed area. I currently (mis)use a `ChoroplethViz` to accomplish that, using a single colour stop and a property that's common across all my features. That almost gets the job done for me; the only "issue" is that the legend doesn't show anything useful, since I'm misusing the `ChoroplethViz` type.

Question: would there be any interest in having a way to hide the legend?

I've a few ideas, the simplest being a boolean _`should_show_legend=True`_ argument in either the constructor or `ChoroplethViz.show()`, but I wanted to check with y'all first in case the solution to my problem is ~~more coffee~~ already hiding in plain sight somewhere in the documentation. Which I swear I've read several times over.

Thanks!

**Comment by ryanbaumann** [comment]
I'm in favor of a `legend=True` option @bchowTWC, where the default parameter value is `True`.  This could be added as a base parameter to all visualizations, along with `style` and `access_token`.

**Comment by akacarlyann** [comment]
Work in progress at #100 :)

**Comment by ryanbaumann** [comment]
Agree with that approach @akacarlyann - generate the div in the javascript function instead of using more CSS magic to conditionally show/hide the legend

**Comment by akacarlyann** [comment]
For next steps on this, I think the best things would be:
- [ ] smart text wrapping/scaling in legend item text
- [ ] a variable radius legend for graduated circle viz 
- [ ] variable width legend for linestring viz
- [ ] some other support for multi-variable legends
- [ ] legend placement controls (currently always lower right of map)

**Comment by ryanbaumann** [comment]
Closed in #100 - let's open a new issue to track improvements @akacarlyann
