### ISSUE TITLE
Circle Overlapping

### ISSUE THREAD

**Issue by ankit6883** [mapbox/mapboxgl-jupyter#84]
I am showing near 40k data and someplace circle overlapping is happening I want to see all circle separately.is there any property i can use.

**Comment by akacarlyann** [comment]
Hi @ankit6883 !  Any chance you can provide a screenshot of what you're seeing?  Are you using a CircleViz?

**Comment by ankit6883** [comment]
![issueheatmap - copy](https://user-images.githubusercontent.com/32532587/38076237-a46817b2-3352-11e8-9b40-5b8b0cb3dd5c.PNG)

**Comment by akacarlyann** [comment]
It looks like you are asking about multiple data layers in a single map. Is that right?  This is on the roadmap for mapboxgl-jupyter but there's no support for it just yet.  

I'd recommend reducing the circle radius size and decreasing the opacity if you want the invisible green points to show through.  The other thing you could do is edit the z-order of both layers so that the green points lie on top of your yellow-to-red color mapped points.  Hope that helps!  Here's how you would initialize the CircleViz with a radius of 1.0 and opacity of 0.5 (50%).

```
import os
from mapboxgl.utils import *
from mapboxgl.viz import *

# Must be a public token, starting with `pk`
token = os.getenv('MAPBOX_ACCESS_TOKEN')

# define "breaks" for color mapping (I just put in a generic example b/c I don't know the scale of your data)
color_breaks = [0, 10, 100, 1000]

# define color_property, the GeoJSON feature property used to assign color to the point
color_property = '???'

# initialize the MapboxGL-Jupyter map visualization, where geoShapes is a valid GeoJSON object containing point features
viz = CircleViz(geoShapes,
                color_property = color_property,
                color_stops=create_color_stops(color_breaks, colors='YlOrRd'),
                radius = 1,
                opacity=0.5,
                below_layer = 'waterway-label')

viz.show()
```

**Comment by ryanbaumann** [comment]
Do you have any followup questions @ankit6883 ?
